#ifndef GUARD_CONSTANTS_LAYOUTS_H
#define GUARD_CONSTANTS_LAYOUTS_H

//
// DO NOT MODIFY THIS FILE! It is auto-generated from data/layouts/layouts.json
//

#define LAYOUT_POKEMON_CENTER_1F 1
#define LAYOUT_POKEMON_CENTER_2F 2
#define LAYOUT_MART 3
#define LAYOUT_SEATON_TOWN 4
#define LAYOUT_INSIDE_OF_SHIP 5
#define LAYOUT_JOLTIK_CAVE 6
#define LAYOUT_ROUTE1 7

#endif // GUARD_CONSTANTS_LAYOUTS_H
